CREATE DATABASE IF NOT EXISTS village_cricket;
USE village_cricket;

CREATE TABLE IF NOT EXISTS matches (
  id VARCHAR(36) PRIMARY KEY,
  team_a VARCHAR(120) NOT NULL,
  team_b VARCHAR(120) NOT NULL,
  max_overs INT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'in_progress',
  winner VARCHAR(255) NOT NULL DEFAULT '',
  score_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
